import React, { useState } from "react";
import { useHealth } from "../context/HealthContext";
import {
  FileText,
  Printer,
  Copy,
  Check,
  X,
  Sparkles,
  ShieldCheck,
  HelpCircle,
  Pill,
  Activity,
  Calendar,
  Download,
  Share2,
} from "lucide-react";

interface DoctorBriefModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const DoctorBriefModal: React.FC<DoctorBriefModalProps> = ({ isOpen, onClose }) => {
  const { user, activeLifeStage, todayLog, patterns, vaultDocs, formatTerm } = useHealth();
  const [copied, setCopied] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);

  if (!isOpen) return null;

  const handleCopy = () => {
    const briefText = `VELORA CLINICAL HEALTH BRIEF
Patient: ${user.name} | Age: 31 | Stage: ${activeLifeStage}
Date Generated: August 21, 2026

1. CLINICAL CYCLE & BIOMETRIC PROFILE
- Typical Cycle Length: ${user.cycleLength || 29} days (Variation ±1.5 days)
- Typical Period Duration: ${user.periodLength || 5} days
- Current Cycle Day: Day 18 (Mid-Luteal Phase)
- Average Resting Sleep: 7.6 hrs/night

2. OBSERVED SYMPTOM PATTERNS (LONGITUDINAL)
${patterns.map((p) => `- ${p.title}: "${p.description}" (${p.occurrenceFrequency})`).join("\n")}

3. CURRENT MEDICATIONS & SUPPLEMENTS
- Prenatal Multivitamin with Methylfolate (1 daily)
- Magnesium Bisglycinate 300mg (1 nightly)

4. RECENT LAB SUMMARY
${vaultDocs
  .flatMap((d) => d.extractedFacts || [])
  .map((f) => `- ${f.parameter}: ${f.value} (Ref: ${f.referenceRange || "Standard"}) [Status: ${f.status}]`)
  .join("\n")}

5. PATIENT QUESTIONS FOR APPOINTMENT
- Given recurring Day 21-24 tension headaches, could tracking luteal progesterone or checking iron saturation be beneficial?
- Are my current ferritin (22 ng/mL) and vitamin D levels optimal for sustained energy?

*Note: Generated by Velora as an objective patient-authored summary.*`;

    navigator.clipboard.writeText(briefText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-xs">
      <div className="bg-white rounded-2xl max-w-3xl w-full shadow-2xl border border-[#FFDADA] overflow-hidden flex flex-col max-h-[92vh] animate-in fade-in zoom-in-95 duration-150">
        {/* Header Actions */}
        <div className="p-5 border-b border-[#FFDADA] bg-[#FFF5F7] flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-xl bg-[#FF788D] text-white shadow-2xs">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-lg font-serif font-bold text-[#2D2226]">
                Velora Doctor Brief™
              </h2>
              <p className="text-xs text-[#735E65]">
                1-Page Objective Clinical Summary for your Healthcare Provider
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="px-3 py-1.5 bg-white border border-[#FFDADA] hover:bg-[#FFF5F7] text-[#2D2226] text-xs font-semibold rounded-xl transition-all flex items-center gap-1.5 cursor-pointer shadow-2xs"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-[#FF788D]" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? "Copied!" : "Copy for Portal"}</span>
            </button>
            <button
              onClick={handlePrint}
              className="px-3 py-1.5 bg-white border border-[#FFDADA] hover:bg-[#FFF5F7] text-[#2D2226] text-xs font-semibold rounded-xl transition-all flex items-center gap-1.5 cursor-pointer shadow-2xs"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / PDF</span>
            </button>
            <button
              onClick={onClose}
              className="p-1.5 text-[#8E7A81] hover:text-[#2D2226] rounded-lg hover:bg-[#FFF5F7] cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable Clinical Sheet */}
        <div className="p-6 sm:p-8 overflow-y-auto space-y-6 text-[#2D2226] bg-white">
          {/* Clinical Header */}
          <div className="border-b-2 border-[#2D2226] pb-4 flex flex-col sm:flex-row justify-between items-start sm:items-end gap-3">
            <div>
              <span className="text-[10px] font-bold tracking-widest text-[#D9455D] uppercase">
                Patient-Authored Health Summary
              </span>
              <h1 className="text-2xl font-serif font-bold text-[#2D2226] mt-0.5">
                {user.name}
              </h1>
              <p className="text-xs text-[#735E65]">
                DOB: 1995-04-12 (31 yrs) · Stage: {activeLifeStage.replace("_", " ").toUpperCase()}
              </p>
            </div>
            <div className="text-left sm:text-right text-xs text-[#8E7A81] space-y-0.5">
              <p className="font-semibold text-[#2D2226]">Visit Date: August 21, 2026</p>
              <p>Generated via Velora Encrypted Health Companion</p>
            </div>
          </div>

          {/* Section 1: Cycle & Biometric Baseline */}
          <div className="space-y-2">
            <h3 className="text-xs font-bold text-[#2D2226] uppercase tracking-wider flex items-center gap-1.5 border-b border-[#FFDADA] pb-1">
              <Calendar className="w-3.5 h-3.5 text-[#FF788D]" />
              <span>1. Physiological Rhythm & Baseline</span>
            </h3>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs">
              <div className="p-2.5 rounded-lg bg-[#FFF5F7] border border-[#FFDADA]">
                <span className="text-[#8E7A81] block text-[11px]">Cycle Length</span>
                <span className="font-bold text-[#2D2226]">{user.cycleLength || 29} Days (±1.5d)</span>
              </div>
              <div className="p-2.5 rounded-lg bg-[#FFF5F7] border border-[#FFDADA]">
                <span className="text-[#8E7A81] block text-[11px]">Period Duration</span>
                <span className="font-bold text-[#2D2226]">{user.periodLength || 5} Days</span>
              </div>
              <div className="p-2.5 rounded-lg bg-[#FFF5F7] border border-[#FFDADA]">
                <span className="text-[#8E7A81] block text-[11px]">Today's Status</span>
                <span className="font-bold text-[#2D2226]">Cycle Day 18 (Luteal)</span>
              </div>
              <div className="p-2.5 rounded-lg bg-[#FFF5F7] border border-[#FFDADA]">
                <span className="text-[#8E7A81] block text-[11px]">Mean Sleep</span>
                <span className="font-bold text-[#2D2226]">7.6 hrs/night</span>
              </div>
            </div>
          </div>

          {/* Section 2: Observed Body Patterns */}
          <div className="space-y-2">
            <h3 className="text-xs font-bold text-[#2D2226] uppercase tracking-wider flex items-center gap-1.5 border-b border-[#FFDADA] pb-1">
              <Activity className="w-3.5 h-3.5 text-[#FF788D]" />
              <span>2. Observed Longitudinal Symptom Correlations</span>
            </h3>
            <div className="space-y-2">
              {patterns.map((p) => (
                <div key={p.id} className="p-3 bg-[#FFF5F7] rounded-xl border border-[#FFDADA] text-xs space-y-1">
                  <div className="flex justify-between items-center">
                    <span className="font-bold text-[#2D2226]">{p.title}</span>
                    <span className="text-[10px] font-semibold bg-[#FFF5F7] text-[#D9455D] px-2 py-0.5 rounded border border-[#FFDADA]">
                      {p.occurrenceFrequency}
                    </span>
                  </div>
                  <p className="text-[#735E65]">{p.description}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Section 3: Active Medications & Supplements */}
          <div className="space-y-2">
            <h3 className="text-xs font-bold text-[#2D2226] uppercase tracking-wider flex items-center gap-1.5 border-b border-[#FFDADA] pb-1">
              <Pill className="w-3.5 h-3.5 text-[#FF788D]" />
              <span>3. Active Regimens & Supplements</span>
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
              <div className="p-2.5 rounded-lg bg-[#FFF5F7] border border-[#FFDADA]">
                <span className="font-semibold text-[#2D2226] block">Prenatal Multivitamin with Methylfolate</span>
                <span className="text-[#735E65]">1 capsule daily with food · Active</span>
              </div>
              <div className="p-2.5 rounded-lg bg-[#FFF5F7] border border-[#FFDADA]">
                <span className="font-semibold text-[#2D2226] block">Magnesium Bisglycinate 300mg</span>
                <span className="text-[#735E65]">Nightly for neuromuscular relaxation · Active</span>
              </div>
            </div>
          </div>

          {/* Section 4: Extracted Lab Summary */}
          <div className="space-y-2">
            <h3 className="text-xs font-bold text-[#2D2226] uppercase tracking-wider flex items-center gap-1.5 border-b border-[#FFDADA] pb-1">
              <FileText className="w-3.5 h-3.5 text-[#FF788D]" />
              <span>4. Relevant Recent Biomarkers (Quest Diagnostics - 2026-08-05)</span>
            </h3>
            <div className="border border-[#FFDADA] rounded-xl overflow-hidden text-xs">
              <table className="w-full text-left">
                <thead className="bg-[#FFF5F7] text-[#2D2226] border-b border-[#FFDADA]">
                  <tr>
                    <th className="p-2 font-semibold">Test Parameter</th>
                    <th className="p-2 font-semibold">Value</th>
                    <th className="p-2 font-semibold">Reference Interval</th>
                    <th className="p-2 font-semibold">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[#FFDADA]">
                  <tr>
                    <td className="p-2 font-medium">Serum Ferritin</td>
                    <td className="p-2 font-bold text-amber-700">22 ng/mL</td>
                    <td className="p-2 text-[#8E7A81]">15 - 150 ng/mL</td>
                    <td className="p-2 text-amber-700 font-semibold">Low-Normal</td>
                  </tr>
                  <tr>
                    <td className="p-2 font-medium">TSH (Thyroid Stimulating Hormone)</td>
                    <td className="p-2 font-bold text-[#2D2226]">2.1 mIU/L</td>
                    <td className="p-2 text-[#8E7A81]">0.4 - 4.0 mIU/L</td>
                    <td className="p-2 text-[#D9455D] font-semibold">Optimal</td>
                  </tr>
                  <tr>
                    <td className="p-2 font-medium">25-OH Vitamin D</td>
                    <td className="p-2 font-bold text-[#2D2226]">38 ng/mL</td>
                    <td className="p-2 text-[#8E7A81]">30 - 100 ng/mL</td>
                    <td className="p-2 text-[#D9455D] font-semibold">Sufficient</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          {/* Section 5: Patient's Prepared Questions for Doctor */}
          <div className="space-y-2 bg-[#FFF5F7] p-4 rounded-xl border border-[#FFDADA]">
            <h3 className="text-xs font-bold text-[#2D2226] uppercase tracking-wider flex items-center gap-1.5">
              <HelpCircle className="w-3.5 h-3.5 text-[#FF788D]" />
              <span>5. Patient Agenda / Questions for Discussion Today</span>
            </h3>
            <ul className="space-y-1.5 text-xs text-[#2D2226]">
              <li className="flex items-start gap-2">
                <span className="font-bold text-[#FF788D]">1.</span>
                <span>
                  Given recurring Day 21-24 headaches and fatigue, could evaluating iron saturation, transferrin, or mid-luteal progesterone timing provide clarity?
                </span>
              </li>
              <li className="flex items-start gap-2">
                <span className="font-bold text-[#FF788D]">2.</span>
                <span>
                  Is 22 ng/mL ferritin sufficient for my current life stage, or would targeted dietary iron or co-factor supplementation be recommended?
                </span>
              </li>
            </ul>
          </div>

          {/* Legal Notice */}
          <div className="text-[10px] text-[#8E7A81] pt-3 border-t border-[#FFDADA] flex items-center justify-between">
            <span>Prepared by patient via Velora Health Super-App · Non-diagnostic record</span>
            <span>Zero-Knowledge Privacy Verified</span>
          </div>
        </div>

        {/* Modal Footer */}
        <div className="p-4 border-t border-[#FFDADA] bg-[#FFF5F7] flex items-center justify-between">
          <span className="text-xs text-[#8E7A81]">
            Share directly or upload PDF into MyChart / AthenaHealth
          </span>
          <button
            onClick={onClose}
            className="px-5 py-2 text-xs font-semibold text-white bg-[#FF788D] hover:bg-[#E85C71] rounded-xl cursor-pointer shadow-xs"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
